### ISSUE TITLE
MidTerm

### ISSUE THREAD

**Issue by ttlinhnguyen205** [ahquan421/Nhom5_N01#1]
Hi

**Comment by ahquan421** [comment]
he

**Comment by ttlinhnguyen205** [comment]
Bài 1.1 tớ làm như này cậu thấy có hợp lý không ? 
public interface Signal {
    double getBienDo();   
    double getTanSo();  
    double getChuKy();     
    double getBuocSong();  
}

**Comment by ahquan421** [comment]
bạn thêm package BaiLam vào trên cùng

**Comment by ahquan421** [comment]
![image](https://github.com/user-attachments/assets/def08c9a-1802-445d-a417-59f9a1959b06)
ý 2được chưa á b

**Comment by ttlinhnguyen205** [comment]
được bạn ơi, bạn xem bài nhé 
![Screenshot 2024-09-10 085449](https://github.com/user-attachments/assets/78fe7205-4ed9-4c46-8b57-1a21a49f50c7)

**Comment by ahquan421** [comment]
bạn ơi chép ra giấy mà hết dòng thì có lùi đầu dòng không

**Comment by ttlinhnguyen205** [comment]
t nghĩ là không bạn ơi

**Comment by ahquan421** [comment]
![image](https://github.com/user-attachments/assets/95700489-cbdb-41dc-820a-6a27a89e5fc1)
bạn xem bài nhé

**Comment by ttlinhnguyen205** [comment]
sao tớ không chạy được file radar này bạn ơi, bạn có giải pháp gì không

**Comment by ahquan421** [comment]
bạn phải làm thêm 1 file main nữa b ơi mới chạy được

**Comment by ttlinhnguyen205** [comment]
à okeee

**Comment by ttlinhnguyen205** [comment]
![image](https://github.com/user-attachments/assets/21a35ae8-8fb8-4ff3-9f5a-934dae2e3591)
bạn xem bài này nha
